name: "Prepare Node Environment"
description: "Prepare Node.js environment and set up caching of dependencies"
outputs:
  cache-hit:
    description: "Forward actions/cache cache-hit output"
    value: ${{ steps.yarn-cache.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
      shell: bash

    - name: Set up Node.js from `.nvmrc`
      uses: actions/setup-node@v2
      with:
        node-version-file: ".nvmrc"

    - name: Cache all dependencies
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: |
          **/node_modules
          **/.eslintcache
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
